site_name: Mon site
site_url: http://localhost:8000/

theme:
  name: 'mkdocs'
  color_mode: 'auto' 
  user_color_mode_toggle: true

extra_css:
  - _static/style.css

plugins:
  - search
  - rss
  - include-markdown

nav:
  - Accueil: 
    - Actualités PSMN: Accueil/Actualites.md
    - Partenaires:
      - ENS: Accueil/Partenaires/ENS.md
      - AURA: Accueil/Partenaires/AURA.md
  - Informations:
    - News: Informations/News.md
    - News25: Informations/News/202501/290125.md
    - Les absences des opérateurs: Informations/Absences.md
    - Les arrêts prévus: Informations/Arrets.md
    - Supports :
      - RES: Informations/Supports/RE.md
      - RIC: Informations/Supports/RIC.md
  - Plateformes:
    - Data Center: Plateformes/DataCenter.md
  - Formation:
    - Formation: Formation/Formation.md
    - Propositions de stage: Formation/Stage.md
  - Science:
    - Projets: Science/Projets.md
    - Publications: Science/Publications2024.md
    - Publications2014: Science/Publications2014.md
    - Publications2015: Science/Publications2015.md
    - Sidus: Science/SidusFR.md 
  - Animation:
    - Projets d'animation scientifique: Animation/PAS.md
  - Réseaux:
    - CECAM: Reseaux/CECAM.md
  - Contacts:
    - Formulaires: Contacts/Formulaires.md

markdown_extensions:
  - pymdownx.extra
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.arithmatex
  - pymdownx.betterem
  - pymdownx.tilde
  - pymdownx.tasklist
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.magiclink
  - pymdownx.emoji
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.progressbar
  - pymdownx.snippets
  - pymdownx.critic
  - pymdownx.highlight
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.progressbar
  - pymdownx.tasklist
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.arithmatex
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.keys

